/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpus;

import java.awt.HeadlessException;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;

/**
 *
 * @author Hafizh Ak
 */
public class home_page extends javax.swing.JFrame {
     
    public home_page() {
        initComponents();
        tampil_data();
        tblbuku.setAutoCreateRowSorter(true);
    }
    
    private void bersih() {
        txtidbuku.setText(null);
        txtjudul.setText(null);
        txtpengarang.setText(null);
        txtpenerbit.setText(null);
        txtpeminjam.setText(null);
        txttglpinj.setDate(null);
        txttglkemb.setCalendar(null);
        txtidbuku.enable();
    }
    
    private void tampil_data() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("ID Buku");
        model.addColumn("Judul Buku");
        model.addColumn("Peminjam");
        model.addColumn("Pengarang");
        model.addColumn("Penerbit");
        model.addColumn("Tgl Pinjam");
        model.addColumn("Tgl Kembali");
        
        String cari = txtcari.getText();
        try {
            int i = 1;
            String sql = "SELECT * FROM tbbuku WHERE idBuku LIKE '%"+cari+"%'";
            java.sql.Connection conn = (Connection)config.congfigDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while (res.next()) {
                model.addRow(new Object[]{i++, res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5), res.getString(6), res.getString(7)});
            }
            tblbuku.setModel(model);
            
        } catch (SQLException e) {
            System.out.println("Error : " + e.getMessage());
        }
    }
    
    public static Date getTanggalFromtTable(JTable table, int kolom) {
        JTable tabel = table;
        String strtgl = String.valueOf(tabel.getValueAt(tabel.getSelectedRow(), kolom));
        Date tanggal = null;
        try {
            tanggal = new SimpleDateFormat("yyyy-MM-dd").parse(strtgl);
        } catch (ParseException ex) {
            Logger.getLogger(home_page.class.getName()).log(Level.SEVERE, null, ex);
        }
        return tanggal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        homebtn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bookbtn = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        logouttext = new javax.swing.JLabel();
        mainpanel = new javax.swing.JPanel();
        homepanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        bookspanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        inputpanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtidbuku = new javax.swing.JTextField();
        txtpeminjam = new javax.swing.JTextField();
        txtjudul = new javax.swing.JTextField();
        txtpengarang = new javax.swing.JTextField();
        simpanbtn = new javax.swing.JButton();
        editbtn = new javax.swing.JButton();
        hapusbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbuku = new javax.swing.JTable();
        bersihbtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtpenerbit = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txttglpinj = new com.toedter.calendar.JDateChooser();
        txttglkemb = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        txtcari = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perpus onlen");

        background.setBackground(new java.awt.Color(26, 26, 26));

        sidebar.setBackground(new java.awt.Color(204, 94, 9));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perpus/open-book.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(245, 245, 245));
        jLabel2.setText("PERPUS");

        homebtn.setBackground(new java.awt.Color(245, 245, 245));
        homebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homebtnMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("HOME");

        javax.swing.GroupLayout homebtnLayout = new javax.swing.GroupLayout(homebtn);
        homebtn.setLayout(homebtnLayout);
        homebtnLayout.setHorizontalGroup(
            homebtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homebtnLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        homebtnLayout.setVerticalGroup(
            homebtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homebtnLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        inputbtn.setBackground(new java.awt.Color(245, 245, 245));
        inputbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inputbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputbtnMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("ADMINISTRATION");

        javax.swing.GroupLayout inputbtnLayout = new javax.swing.GroupLayout(inputbtn);
        inputbtn.setLayout(inputbtnLayout);
        inputbtnLayout.setHorizontalGroup(
            inputbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputbtnLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        inputbtnLayout.setVerticalGroup(
            inputbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputbtnLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        bookbtn.setBackground(new java.awt.Color(245, 245, 245));
        bookbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bookbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookbtnMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("BOOKS");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout bookbtnLayout = new javax.swing.GroupLayout(bookbtn);
        bookbtn.setLayout(bookbtnLayout);
        bookbtnLayout.setHorizontalGroup(
            bookbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookbtnLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bookbtnLayout.setVerticalGroup(
            bookbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookbtnLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        logout.setBackground(new java.awt.Color(245, 245, 245));
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        logouttext.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        logouttext.setForeground(new java.awt.Color(203, 0, 0));
        logouttext.setText("LOG OUT");

        javax.swing.GroupLayout logoutLayout = new javax.swing.GroupLayout(logout);
        logout.setLayout(logoutLayout);
        logoutLayout.setHorizontalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(logouttext, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        logoutLayout.setVerticalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(logouttext, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(inputbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bookbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3))
                    .addComponent(jLabel2)))
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(98, 98, 98)
                .addComponent(homebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(inputbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(bookbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainpanel.setBackground(new java.awt.Color(26, 26, 26));
        mainpanel.setLayout(new java.awt.CardLayout());

        homepanel.setBackground(new java.awt.Color(26, 26, 26));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("APLIKASI SISTEM PERPUSTAKAAN");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout homepanelLayout = new javax.swing.GroupLayout(homepanel);
        homepanel.setLayout(homepanelLayout);
        homepanelLayout.setHorizontalGroup(
            homepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homepanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        homepanelLayout.setVerticalGroup(
            homepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homepanelLayout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel18)
                .addGap(244, 244, 244)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(270, 270, 270))
        );

        mainpanel.add(homepanel, "card2");

        bookspanel.setBackground(new java.awt.Color(26, 26, 26));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("BOOKS PANEL");

        javax.swing.GroupLayout bookspanelLayout = new javax.swing.GroupLayout(bookspanel);
        bookspanel.setLayout(bookspanelLayout);
        bookspanelLayout.setHorizontalGroup(
            bookspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookspanelLayout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(0, 399, Short.MAX_VALUE))
        );
        bookspanelLayout.setVerticalGroup(
            bookspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookspanelLayout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(0, 686, Short.MAX_VALUE))
        );

        mainpanel.add(bookspanel, "card4");

        inputpanel.setBackground(new java.awt.Color(26, 26, 26));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ADMINISTRASI PERPUSTAKAAN");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(245, 245, 245));
        jLabel6.setText("Id Buku");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(245, 245, 245));
        jLabel7.setText("Judul Buku");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(245, 245, 245));
        jLabel8.setText("Peminjam");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(245, 245, 245));
        jLabel13.setText("Pengarang");

        txtidbuku.setBackground(new java.awt.Color(245, 245, 245));
        txtidbuku.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtpeminjam.setBackground(new java.awt.Color(245, 245, 245));
        txtpeminjam.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtpeminjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpeminjamActionPerformed(evt);
            }
        });

        txtjudul.setBackground(new java.awt.Color(245, 245, 245));
        txtjudul.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtpengarang.setBackground(new java.awt.Color(245, 245, 245));
        txtpengarang.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        simpanbtn.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        simpanbtn.setText("Simpan");
        simpanbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanbtnActionPerformed(evt);
            }
        });

        editbtn.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        editbtn.setText("Ubah");
        editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbtnActionPerformed(evt);
            }
        });

        hapusbtn.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        hapusbtn.setText("Hapus");
        hapusbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusbtnActionPerformed(evt);
            }
        });

        tblbuku.setBackground(new java.awt.Color(245, 245, 245));
        tblbuku.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tblbuku.setForeground(new java.awt.Color(26, 26, 26));
        tblbuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Id Buku", "Judul Buku", "Peminjam", "Pengarang", "Penerbit", "Tgl Pinjam", "Tgl Kembali"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblbuku.setAutoscrolls(false);
        tblbuku.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblbuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblbuku);

        bersihbtn.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        bersihbtn.setText("Bersih");
        bersihbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bersihbtnActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(245, 245, 245));
        jLabel14.setText("Penerbit");

        txtpenerbit.setBackground(new java.awt.Color(245, 245, 245));
        txtpenerbit.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(245, 245, 245));
        jLabel15.setText("Tgl Pinjam");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(245, 245, 245));
        jLabel16.setText("Tgl Kembali");

        txtcari.setBackground(new java.awt.Color(245, 245, 245));
        txtcari.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcariKeyReleased(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(245, 245, 245));
        jLabel17.setText("Cari Data");

        javax.swing.GroupLayout inputpanelLayout = new javax.swing.GroupLayout(inputpanel);
        inputpanel.setLayout(inputpanelLayout);
        inputpanelLayout.setHorizontalGroup(
            inputpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(inputpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputpanelLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputpanelLayout.createSequentialGroup()
                        .addGroup(inputpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel13)
                            .addComponent(jLabel6)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(41, 41, 41)
                        .addGroup(inputpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtidbuku, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtjudul, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtpeminjam, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtpengarang, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtpenerbit, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, inputpanelLayout.createSequentialGroup()
                                .addComponent(simpanbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(20, 20, 20)
                                .addComponent(editbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(20, 20, 20)
                                .addComponent(hapusbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(22, 22, 22)
                                .addComponent(bersihbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txttglpinj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txttglkemb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25))
                    .addGroup(inputpanelLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(inputpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(inputpanelLayout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(424, 424, 424))
                            .addComponent(txtcari))
                        .addGap(85, 85, 85))))
        );
        inputpanelLayout.setVerticalGroup(
            inputpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(46, 46, 46)
                .addGroup(inputpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtidbuku))
                .addGap(18, 18, 18)
                .addGroup(inputpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtjudul)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(inputpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpeminjam)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(inputpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpengarang)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(inputpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpenerbit)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(inputpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(txttglpinj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(inputpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(txttglkemb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(inputpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bersihbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcari)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainpanel.add(inputpanel, "card3");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Anda yakin akan keluar?", "PERINGATAN", dialogBtn);
        
        if (dialogResult == 0) {
            login login = new login();
            login.show();
            dispose();
        } 
    }//GEN-LAST:event_logoutMouseClicked

    private void homebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebtnMouseClicked
        // remove panel
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();

        // add panel
        mainpanel.add(homepanel);
        mainpanel.repaint();
        mainpanel.revalidate();
    }//GEN-LAST:event_homebtnMouseClicked

    private void inputbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputbtnMouseClicked
        // TODO add your handling code here:
        
        // remove panel
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();

        // add panel
        mainpanel.add(inputpanel);
        mainpanel.repaint();
        mainpanel.revalidate();
    }//GEN-LAST:event_inputbtnMouseClicked

    private void bookbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookbtnMouseClicked
        // TODO add your handling code here:
        
          // remove panel
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();

        // add panel
        mainpanel.add(bookspanel);
        mainpanel.repaint();
        mainpanel.revalidate();
    }//GEN-LAST:event_bookbtnMouseClicked

    private void tblbukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbukuMouseClicked
        // TODO add your handling code here:
        
        int baris = tblbuku.rowAtPoint(evt.getPoint());
        txtidbuku.disable();
        String idBuku = tblbuku.getValueAt(baris, 1).toString();
        txtidbuku.setText(idBuku);
        String judulBuku = tblbuku.getValueAt(baris, 2).toString();
        txtjudul.setText(judulBuku);
        String peminjam = tblbuku.getValueAt(baris, 3).toString();
        txtpeminjam.setText(peminjam);
        String pengarang = tblbuku.getValueAt(baris, 4).toString();
        txtpengarang.setText(pengarang);
        String penerbit = tblbuku.getValueAt(baris, 5).toString();
        txtpenerbit.setText(penerbit);
        txttglpinj.setDate(getTanggalFromtTable(tblbuku, 6));
        txttglkemb.setDate(getTanggalFromtTable(tblbuku, 7));
        
    }//GEN-LAST:event_tblbukuMouseClicked

    private void simpanbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanbtnActionPerformed
        // TODO add your handling code here
        if (txtjudul.getText().equals("") || txtpengarang.getText().equals("") || txtpeminjam.getText().equals("") || txtpenerbit.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Isi Semua Data ", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            String formattgl = "yyyy-MM-dd";
            SimpleDateFormat frmt = new SimpleDateFormat(formattgl);
            String tanggalpinj = String.valueOf(frmt.format(txttglpinj.getDate()));
            String tanggalkemb = String.valueOf(frmt.format(txttglkemb.getDate()));
            try {
                String sql = "INSERT INTO tbbuku VALUES ('" +txtidbuku.getText()+ "', '" +txtjudul.getText()+ "', '" +txtpeminjam.getText()+ "', '" +txtpengarang.getText()+ "', '" +txtpenerbit.getText()+ "', '" +tanggalpinj+ "', '" +tanggalkemb+ "');"; 
                java.sql.Connection conn = (Connection)config.congfigDB();
                java.sql.PreparedStatement preps = conn.prepareStatement(sql);
                preps.execute();
                JOptionPane.showMessageDialog(null, "Berhasil menyimpan data");
                
                tampil_data();
                bersih();
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Err", JOptionPane.ERROR_MESSAGE);
            } 
        } 
    }//GEN-LAST:event_simpanbtnActionPerformed

    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtnActionPerformed
        // TODO add your handling code here:
         if (txtidbuku.getText().equals("") ||txtjudul.getText().equals("") || txtpengarang.getText().equals("") || txtpeminjam.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Pilih data yang akan diubah", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            int dialogBtn = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "Record yang dipilih akan diedit?", "PERINGATAN", dialogBtn);
        
            if (dialogResult == 0) {  
            try {
                String formattgl = "yyyy-MM-dd";
                SimpleDateFormat frmt = new SimpleDateFormat(formattgl);
                String tanggalpinj = String.valueOf(frmt.format(txttglpinj.getDate()));
                String tanggalkemb = String.valueOf(frmt.format(txttglkemb.getDate()));  
                String sql = "UPDATE tbbuku SET namaBuku='" +txtjudul.getText()+ "', peminjam='" +txtpeminjam.getText()+ "', pengarang='" +txtpengarang.getText()+ "',  penerbit='" +txtpenerbit.getText()+ "',  tanggalpinj='" +tanggalpinj+ "',  tanggalkem='" +tanggalkemb+ "' WHERE tbbuku.idBuku='" +txtidbuku.getText()+ "';"; 
                java.sql.Connection conn = (Connection)config.congfigDB();
                java.sql.PreparedStatement preps = conn.prepareStatement(sql);
                preps.execute();
                JOptionPane.showMessageDialog(null, "Berhasil mengubah data");
                
                tampil_data();
                bersih();
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Err", JOptionPane.ERROR_MESSAGE);
            } 
            }
        } 
    }//GEN-LAST:event_editbtnActionPerformed

    private void hapusbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusbtnActionPerformed
        // TODO add your handling code here:
        if (txtidbuku.getText().equals("") ||txtjudul.getText().equals("") || txtpengarang.getText().equals("") || txtpeminjam.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Pilih data yang akan dihapus", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            int dialogBtn = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "Record yang dipilih akan dihapus?", "PERINGATAN", dialogBtn);
        
            if (dialogResult == 0) {
                try {
                    String sql = "DELETE FROM tbbuku WHERE tbbuku.idBuku='" +txtidbuku.getText()+ "'";
                    java.sql.Connection conn = (Connection)config.congfigDB();
                    java.sql.PreparedStatement preps = conn.prepareStatement(sql);
                    preps.execute();
                    JOptionPane.showMessageDialog(null, "Berhasil menghapus data");

                    tampil_data();
                    bersih();
                } catch (HeadlessException | SQLException e) {
                     JOptionPane.showMessageDialog(this, e.getMessage(), "Err", JOptionPane.ERROR_MESSAGE);
                }
            } 
        }
    }//GEN-LAST:event_hapusbtnActionPerformed

    private void bersihbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bersihbtnActionPerformed
        // TODO add your handling code here:
        bersih();
        tampil_data();
    }//GEN-LAST:event_bersihbtnActionPerformed

    private void txtpeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpeminjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpeminjamActionPerformed

    private void txtcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyReleased
        // TODO add your handling code here:
        tampil_data();
    }//GEN-LAST:event_txtcariKeyReleased
    
     
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton bersihbtn;
    private javax.swing.JPanel bookbtn;
    private javax.swing.JPanel bookspanel;
    private javax.swing.JButton editbtn;
    private javax.swing.JButton hapusbtn;
    private javax.swing.JPanel homebtn;
    private javax.swing.JPanel homepanel;
    public static final javax.swing.JPanel inputbtn = new javax.swing.JPanel();
    private javax.swing.JPanel inputpanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel logout;
    private javax.swing.JLabel logouttext;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JPanel sidebar;
    private javax.swing.JButton simpanbtn;
    private javax.swing.JTable tblbuku;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtidbuku;
    private javax.swing.JTextField txtjudul;
    private javax.swing.JTextField txtpeminjam;
    private javax.swing.JTextField txtpenerbit;
    private javax.swing.JTextField txtpengarang;
    private com.toedter.calendar.JDateChooser txttglkemb;
    private com.toedter.calendar.JDateChooser txttglpinj;
    // End of variables declaration//GEN-END:variables
}
